### PR TITLE
fix: Python version indentation in policy file

### PR DESCRIPTION
**Pull request by gclapperton**
The docs have:
```
version: v1.22.1
language-settings: 
python: "2.7"
```

but `python` should be nested under `language-settings`, like so:
```
version: v1.22.1
language-settings: 
  python: "2.7"
```

https://docs.snyk.io/snyk-cli/test-for-vulnerabilities/the-.snyk-file
image

### CODE REVIEW

**Comment by owenmorrill** [comment]
I'm going to leave this for Ann to follow up on since our CLI docs have a separate review process. I anticipate that we'll close this PR out and go through Ann for the changes. Thanks!

**Comment by gclapperton** [comment]
Thanks, Owen. Could you elaborate on what the process is? How do team make or get changes made to the docs?

**Comment by gclapperton** [comment]
Perhaps you or Ann could update the Slack thread with progress or a link of where it could be tracked? https://snyk.slack.com/archives/CFTAUCYQ7/p1666642293665979

**Comment by gclapperton** [comment]
Ok, just so I'm clear (and can report back to the Python team), we should ask #ask-content to make any changes to the CLI docs? But PRs are ok for changes to language specific documentation? Does this also go for other non-CLI changes?

**Pull request merged**
